---
- name: Create an instance
  hosts: localhost
  gather_facts: no

  vars:
    gcp_cred_file: /etc/ansible/key.json
    gcp_project: angelic-button-318912
    gcp_cred_kind: serviceaccount
    zone: "us-central1-a"
    region: "us-central1"

  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: 'disk-bastilion'
        size_gb: 30
        source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: disk
    - name: create a address
      gcp_compute_address:
        name: 'address-bastilion'
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address
    - name: create a instance
      gcp_compute_instance:
        state: present
        name: bastilion-instance
        machine_type: n1-standard-1
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - network: null # use default
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address }}"
                type: 'ONE_TO_ONE_NAT'
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
      register: instance
